### ISSUE TITLE
Hi, I am using thor labs controller (APT BBD202). Can anybody please help me how do I find the hardware type of the controller and execute it in the python?

### ISSUE THREAD

**Issue by bhushansavalia** [mcleung/PyAPT#20]
_Originally posted by @bhushansavalia in https://github.com/mcleu/PyAPT/issues/18#issuecomment-447773788_

**Comment by mcleu** [comment]
Hi,

The HW type are specified by Thorlabs. Can you try it with type 44? (It's for BBD10X).
Otherwise, I would contact Thorlabs for an updated DLL.

Note that this is no longer maintained and updated, and I suggest you use Instrumental to control your servo. https://github.com/mabuchilab/Instrumental/

**Comment by bhushansavalia** [comment]
Hi,
I tried wit type 44 and it wprked. 
Thank you for the response.
