### ISSUE TITLE
Old DLL not compatible with KDC101

### ISSUE THREAD

**Issue by vatgh** [mcleung/PyAPT#9]
In principle the code seems to work fine with the Thorlabs Kinesis KDC101 controller using HWTYPE=31. However, only after replacing the DLL (APT.dll and APT.lib) with copies of the latest one from Thorlabs (found in the folders of the Thorlabs APT software after installing it or here [APTDLL.zip](https://github.com/mcleung/PyAPT/files/1179308/APTDLL.zip) ).

**Comment by saurabhX9** [comment]
Hey People, I am thankful for such useful code.
I have been able to go through all the compatibility issues and this code finally runs for me; but I have no idea what serial number to put in for KDC 101, can somebody help me?
I am able to run this GUI:

![gui](https://user-images.githubusercontent.com/33573072/41843013-011bbfc8-788a-11e8-8e31-cd4469f31f97.JPG)


I get this error when i click "connect" ; of course because i don't know the serial number.

Traceback (most recent call last):
  File "C:\Python365\progs\stage\PyAPT\myGUI.py", line 198, in connectAPT
    self._Motor_.initializeHardwareDevice()
  File "C:\Python365\progs\stage\PyAPT\PyAPT.py", line 113, in initializeHardwareDevice
    raise Exception('Connection Failed. Check Serial Number!')
Exception: Connection Failed. Check Serial Number!

**Comment by mcleu** [comment]
Serial number will be printed on your motor controller. It’s hardcoded by
the manufacturer (Thorlabs). You can run their APT program to get it.
